{% set name = "shapeworks" %}
{% set version = "6.0b" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  binary_relocation: False
#   number: 0
#   script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  # host:
  #   - appdirs
  #   - imageio
  #   - meshio >=4.0.3
  #   - numpy
  #   - pillow
  #   - pip
  #   - python
  #   - scooby >=0.5.1
  #   - vtk
  run:
    - notebook
    - numpy 1.19.1
    - python 3.7.8
    - vtk

# test:
#   imports:
#     - shapeworks
#     - shapeworks.utils
    # - pyvista.demos
    # - pyvista.examples
    # - pyvista.plotting
    # - pyvista.utilities

about:
  home: "https://github.com/SCIInstitute/ShapeWorks"
  license: GPL
  license_family: GPL
  license_file: 
  summary: "ShapeWorks"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - cchriste
    - archanasri
    - akenmorris
    - sheryjoe
