name: Linux Build

on:
  push:
    branches:
      - master
      - action_ccache
    tags:
    - '*'
  pull_request:

env:
  CCACHE_VERSION: 3.7.7

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:

    - name: Download ccache
      id: ccache
      shell: cmake -P {0}
      run: |
        set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v$ENV{CCACHE_VERSION}/${{ runner.os }}.tar.xz")
        file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)

    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")

    - name: ccache cache files
      uses: actions/cache@v1.1.0
      with:
        path: .ccache
        key: ${{ matrix.config.name }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ matrix.config.name }}-ccache-
    
    - name: Setup Conda
      uses: goanpeca/setup-miniconda@v1
      with:
          miniconda-version: 'latest'

    - name: Conda info
      run: conda info

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Get tags
      run: git fetch --unshallow origin +refs/tags/*:refs/tags/*
        
    - name: conda installs
      shell: bash -l {0}
      run: source ./conda_installs.sh

    - name: activate shapeworks
      shell: bash -l {0}
      run: conda activate shapeworks
      
    - name: Acquire LinuxDeployQt
      run: curl -L -o $HOME/linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/5/linuxdeployqt-5-x86_64.AppImage && chmod +x $HOME/linuxdeployqt

    - name: Install Qt
      uses: ouuan/install-qt-action@v2.3.1
      with:
        version: "5.9.9"

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v1
      with:
        path: ~/install
        key: ${{ runner.os }}-${{ hashFiles('**/build_dependencies.sh') }}

    - name: Build dependencies
      shell: bash -l {0}
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: INSTALL_DIR=$HOME/install BUILD_DIR=$HOME/build ./build_dependencies.sh

    - name: cmake
      shell: bash -l {0}
      run: mkdir build && cd build && cmake -DVXL_DIR=$HOME/install/share/vxl/cmake -DITK_DIR=$HOME/install/lib/cmake/ITK-5.0 -DVTK_DIR=$HOME/install/lib/cmake/vtk-8.2 -DEigen3_DIR=$HOME/install/share/eigen3/cmake -DCMAKE_BUILD_TYPE=Release -DSHAPEWORKS_SUPERBUILD=OFF -DBuild_Studio=ON -DBuild_View2=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/shapeworks-install ..

    - name: make
      shell: bash -l {0}
      run: cd build && make -j4

    - name: make install
      shell: bash -l {0}
      run: cd build && make install
      
    - name: Remove Qt SQL Stuff
      run: rm /home/runner/work/ShapeWorks/Qt/5.9.9/gcc_64/plugins/sqldrivers/libqsqlmysql.so /home/runner/work/ShapeWorks/Qt/5.9.9/gcc_64/plugins/sqldrivers/libqsqlpsql.so

    - name: Build Binary Package
      run: pwd ; ls ; PATH=$HOME:$PATH ./Support/package.sh tag ${GITHUB_WORKSPACE}/shapeworks-install $HOME/install ; ls /home/runner/work/ShapeWorks/ShapeWorks/package

    - name: make test
      shell: bash -l {0}
      run: conda activate shapeworks && cd build && ctest -VV
    
    - uses: actions/upload-artifact@v1
      with:
        name: artifact-${{github.sha}}-linux
        path: ${{runner.workspace}}/ShapeWorks/artifacts
