name: Mac Build

on:
  push:
    branches:
      - master
      - build_artifacts
  pull_request:

jobs:
  build:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1

    - name: Acquire 10.13 SDK
      run: curl -L -o $HOME/MacOSX10.13.sdk.tar.xz https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.13.sdk.tar.xz

    - name: Unpack SDK
      run: cd $HOME && brew install gnu-tar && gtar -xf MacOSX10.13.sdk.tar.xz

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/install
        key: ${{ runner.os }}-node
        
    - name: Build dependencies
      run: .github/workflows/build_dependencies.sh

    - name: cmake
      run: mkdir build && cd build && cmake -DVXL_DIR=$HOME/install/share/vxl/cmake -DITK_DIR=$HOME/install/lib/cmake/ITK-5.0 -DVTK_DIR=$HOME/install/lib/cmake/vtk-8.2 -DCMAKE_BUILD_TYPE=Release -DSHAPEWORKS_SUPERBUILD=OFF -DUSE_OPENMP=OFF -DBuild_Studio=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/shapeworks-install -DCMAKE_OSX_SYSROOT="$HOME/MacOSX10.13.sdk" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13" ..

    - name: make
      run: cd build && make -j4

    - name: make test
      run: cd build && make test

    - name: make install
      run: cd build && make install

    - name: Create Installer
      run: pwd ; ls ; ./package.sh shapeworks-${GITHUB_SHA}-mac ${GITHUB_WORKSPACE}/shapeworks-install $HOME/install

    - uses: actions/upload-artifact@v1
      with:
        name: shapeworks-${{github.sha}}-mac.zip
        path: ${{runner.workspace}}/Shapeworks/package/shapeworks-${{github.sha}}-mac
