name: Mac Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1

    - name: Acquire 10.13 SDK
      run: curl -L -o $HOME/MacOSX10.13.sdk.tar.gz http://www.sci.utah.edu/~amorris/MacOSX10.13.sdk.tar.gz

    - name: Unpack SDK
      run: cd $HOME && tar -xzf MacOSX10.13.sdk.tar.gz

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/install
        key: ${{ runner.os }}-${{ hashFiles('**/build_dependencies.sh') }}
        
    - name: Build dependencies
      run: SDKROOT=$HOME/MacOSX10.13.sdk .github/workflows/build_dependencies.sh

    - name: cmake
      run: mkdir build && cd build && cmake -DVXL_DIR=$HOME/install/share/vxl/cmake -DITK_DIR=$HOME/install/lib/cmake/ITK-5.0 -DVTK_DIR=$HOME/install/lib/cmake/vtk-8.2 -DCMAKE_BUILD_TYPE=Release -DSHAPEWORKS_SUPERBUILD=OFF -DUSE_OPENMP=OFF -DBuild_Studio=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/shapeworks-install -DCMAKE_OSX_SYSROOT="$HOME/MacOSX10.13.sdk" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13" ..

    - name: make
      run: cd build && make -j4

    - name: make test
      run: cd build && make test

    - name: make install
      run: cd build && make install

    - name: Build Binary Package
      run: pwd ; ls ; ./package.sh shapeworks-${GITHUB_SHA}-mac ${GITHUB_WORKSPACE}/shapeworks-install $HOME/install

    - uses: actions/upload-artifact@v1
      with:
        name: shapeworks-${{github.sha}}-mac
        path: ${{runner.workspace}}/Shapeworks/package/shapeworks-${{github.sha}}-mac
