name: Linux Build

on:
  push:
    branches:
      - master
      - build_artifacts
  pull_request:

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:

    - uses: actions/checkout@v1

    - name: Acquire LinuxDeployQt
      run: curl -L -o $HOME/linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/5/linuxdeployqt-5-x86_64.AppImaged && chmod +x $HOME/linuxdeployqt

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/install
        key: ${{ runner.os }}-node

    - name: Build dependencies
      run: .github/workflows/build_dependencies.sh

    - name: cmake
      run: mkdir build && cd build && cmake -DVXL_DIR=$HOME/install/share/vxl/cmake -DITK_DIR=$HOME/install/lib/cmake/ITK-5.0 -DVTK_DIR=$HOME/install/lib/cmake/vtk-8.2 -DCMAKE_BUILD_TYPE=Release -DSHAPEWORKS_SUPERBUILD=OFF -DBuild_Studio=ON ..

    - name: make
      run: cd build && make -j4

    - name: make test
      run: cd build && make test

    - name: Build Binary Package
      run: pwd ; ls ; ./package.sh shapeworks-${GITHUB_SHA}-linux ${GITHUB_WORKSPACE}/shapeworks-install $HOME/install
